// Generated by CoffeeScript 1.6.3
var Redison;

Redison = require('../lib');

describe('Connection', function() {
  beforeEach(function(done) {
    this.redison = new Redison({
      servers: ['localhost:6379', 'localhost:6479']
    });
    return done();
  });
  return it('should be connected', function(done) {
    Object.keys(this.redison.clients).length.should.equal(2);
    return done();
  });
});
