// Generated by CoffeeScript 1.7.1
var Redison;

Redison = require('../lib');

describe('Sharding', function() {
  beforeEach(function(done) {
    this.redison = new Redison({
      servers: ['localhost:6379', 'localhost:6479']
    });
    return done();
  });
  return it('keys should be split into different shards', function(done) {
    this.redison.nodeFor('foo').should.not.equal(this.redison.nodeFor('bar'));
    this.redison.set('foo', 'bar');
    this.redison.set('bar', 'foo');
    return done();
  });
});
