// Generated by CoffeeScript 1.7.1
var Multi, Redison, SHARDABLE, UNSHARDABLE, assert, hasher, redis, step, _,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

_ = require('underscore');

assert = require('assert');

redis = require('redis');

step = require('step');

hasher = require('./hasher');

SHARDABLE = ["append", "bitcount", "blpop", "brpop", "debug object", "decr", "decrby", "del", "dump", "exists", "expire", "expireat", "get", "getbit", "getrange", "getset", "hdel", "hexists", "hget", "hgetall", "hincrby", "hincrbyfloat", "hkeys", "hlen", "hmget", "hmset", "hset", "hsetnx", "hvals", "incr", "incrby", "incrbyfloat", "lindex", "linsert", "llen", "lpop", "lpush", "lpushx", "lrange", "lrem", "lset", "ltrim", "mget", "move", "persist", "pexpire", "pexpireat", "psetex", "pttl", "rename", "renamenx", "restore", "rpop", "rpush", "rpushx", "sadd", "scard", "sdiff", "set", "setbit", "setex", "setnx", "setrange", "sinter", "sismember", "smembers", "sort", "spop", "srandmember", "srem", "strlen", "sunion", "ttl", "type", "watch", "zadd", "zcard", "zcount", "zincrby", "zrange", "zrangebyscore", "zrank", "zrem", "zremrangebyrank", "zremrangebyscore", "zrevrange", "zrevrangebyscore", "zrevrank", "zscore"];

UNSHARDABLE = ["auth", "bgrewriteaof", "bgsave", "bitop", "brpoplpush", "client kill", "client list", "client getname", "client setname", "config get", "config set", "config resetstat", "dbsize", "debug segfault", "discard", "echo", "eval", "evalsha", "exec", "flushall", "flushdb", "info", "keys", "lastsave", "migrate", "monitor", "mset", "msetnx", "multi", "object", "ping", "psubscribe", "publish", "punsubscribe", "quit", "randomkey", "rpoplpush", "save", "script exists", "script flush", "script kill", "script load", "sdiffstore", "select", "shutdown", "sinterstore", "slaveof", "slowlog", "smove", "subscribe", "sunionstore", "sync", "time", "unsubscribe", "unwatch", "zinterstore", "zunionstore"];


/*
 * Simple options
 * {
 *   servers: [ 'localhost:6379', 'localhost:6479' ]
 *   password: 'SxZRihb3A5LB6XtrmIU7XOgBAndBbhW47pxx'
 *   database: 3
 * }
 * 
 * Options with scopes
 *
 * {
 *   servers: [
 *     [ ':hash:', [ 'localhost:6579', 'localhost:6679' ] ]
 *     [ 'localhost:6379', 'localhost:6479' ],
 *   ]
 *   password: 'SxZRihb3A5LB6XtrmIU7XOgBAndBbhW47pxx'
 *   database: 3
 * }
 *
 */

Redison = (function() {
  function Redison(options) {
    var client, scoped, _i, _len, _ref, _servers;
    this.options = options;
    this.multi = __bind(this.multi, this);
    this.zinterstore = __bind(this.zinterstore, this);
    this.sinterstore = __bind(this.sinterstore, this);
    this.sinter = __bind(this.sinter, this);
    this.mset = __bind(this.mset, this);
    this.del = __bind(this.del, this);
    assert(!!this.options, "options must be an object");
    if (!this.options.servers) {
      this.options.servers = ['localhost:6379'];
    }
    this.clients = {};
    this.servers = {
      "default": null,
      scopes: {}
    };
    _servers = [];
    if (typeof this.options.servers[0] !== 'string') {
      _ref = this.options.servers;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        scoped = _ref[_i];
        if (Array.isArray(scoped[1])) {
          this.servers.scopes[scoped[0]] = scoped[1];
          _servers = _.union(_servers, scoped[1]);
        } else {
          this.servers["default"] = scoped;
          _servers = _.union(_servers, scoped);
        }
      }
    } else {
      this.servers["default"] = this.options.servers;
      _servers = this.options.servers;
    }
    assert(Array.isArray(this.servers["default"]), "default servers must be set");
    client = _servers.forEach((function(_this) {
      return function(server) {
        var fields;
        fields = server.split(/:/);
        client = redis.createClient(parseInt(fields[1], 10), fields[0]);
        if (_this.options.database) {
          client.select(_this.options.database);
        }
        if (_this.options.password) {
          client.auth(_this.options.password);
        }
        _this.clients[server] = client;
        return client;
      };
    })(this));
    this.connected = true;
    SHARDABLE.forEach((function(_this) {
      return function(command) {
        if (command === 'del' || command === 'sinter') {
          return;
        }
        return _this[command] = _this[command.toUpperCase()] = function() {
          var key, node;
          if (Array.isArray(arguments[0])) {
            key = arguments[0][0];
          } else {
            key = arguments[0];
          }
          node = _this.nodeFor(key);
          client = _this.clients[node];
          return client[command].apply(client, arguments);
        };
      };
    })(this));
    UNSHARDABLE.forEach((function(_this) {
      return function(command) {
        if (command === 'multi' || command === 'mset' || command === 'sinterstore' || command === 'zinterstore') {
          return;
        }
        return _this[command] = _this[command.toUpperCase()] = function() {
          throw new Error("" + command + " is not shardable");
        };
      };
    })(this));
  }

  Redison.prototype.del = function() {
    var args, callback, length, self;
    args = Array.prototype.slice.call(arguments);
    length = args.length;
    callback = null;
    if (typeof args[length - 1] === 'function') {
      callback = args.pop();
    }
    if (Array.isArray(args[0])) {
      args = args[0];
    }
    self = this;
    return step(function() {
      var group;
      group = this.group();
      return args.forEach(function(key, idx) {
        var client, node;
        node = self.nodeFor(key);
        client = self.clients[node];
        return client.del.call(client, key, group());
      });
    }, function(error, groups) {
      if (error) {
        return typeof callback === "function" ? callback(error) : void 0;
      }
      assert(args.length === groups.length, "wrong number of response for 'del', " + args);
      return typeof callback === "function" ? callback(null, 'OK') : void 0;
    });
  };

  Redison.prototype.mset = function() {
    var args, callback, length, self;
    args = Array.prototype.slice.call(arguments);
    length = args.length;
    callback = null;
    if (typeof args[length - 1] === 'function') {
      callback = args.pop();
    }
    if (Array.isArray(args[0])) {
      args = args[0];
    }
    if (args.length % 2 !== 0) {
      throw new Error("wrong arguments given");
    }
    self = this;
    return step(function() {
      var arg, group, idx, _i, _len, _results;
      group = this.group();
      _results = [];
      for (idx = _i = 0, _len = args.length; _i < _len; idx = _i += 2) {
        arg = args[idx];
        _results.push(self.set(arg, args[idx + 1], group()));
      }
      return _results;
    }, function(error, groups) {
      if (error) {
        return typeof callback === "function" ? callback(error) : void 0;
      }
      assert(args.length / 2 === groups.length, "wrong number of response for 'mset', " + args);
      return typeof callback === "function" ? callback(null, 'OK') : void 0;
    });
  };

  Redison.prototype.sinter = function() {
    var arg, args, callback, client, dest_client, dest_key, dest_node, keys, length, migrated_keys, multi, multis, node, remote_nodes, _i, _len, _ref;
    args = Array.prototype.slice.call(arguments);
    length = args.length;
    callback = null;
    if (typeof args[length - 1] === 'function') {
      callback = args.pop();
    }
    if (Array.isArray(args[0])) {
      args = args[0];
    }
    remote_nodes = {};
    multis = [];
    migrated_keys = [];
    dest_key = args[0];
    dest_node = this.nodeFor(dest_key);
    dest_client = this.clients[dest_node];
    _ref = args.slice(1);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      arg = _ref[_i];
      node = this.nodeFor(arg);
      if (remote_nodes[node] == null) {
        remote_nodes[node] = [];
      }
      remote_nodes[node].push(arg);
    }
    for (node in remote_nodes) {
      keys = remote_nodes[node];
      if (node === dest_node) {
        continue;
      }
      client = this.clients[node];
      multi = multis[node] = client.multi();
      keys.forEach(function(key) {
        migrated_keys.push(key);
        return multi.migrate([dest_node.host, dest_node.port, key, dest_node.selected_db]);
      });
    }
    return step(function() {
      var group;
      group = this.group();
      return multis.forEach(function(multi) {
        return multi.exec(group());
      });
    }, function(error, groups) {
      if (error) {
        return typeof callback === "function" ? callback(error) : void 0;
      }
      assert(multis.length === groups.length, "wrong number of response");
      return dest_client.sinter.call(dest_client, args, function() {
        if (migrated_keys.length > 0) {
          dest_client.del(migrated_keys);
        }
        return callback != null ? callback.apply(this, arguments) : void 0;
      });
    });
  };

  Redison.prototype.sinterstore = function() {
    var arg, args, callback, client, dest_client, dest_key, dest_node, keys, length, migrated_keys, multi, multis, node, remote_nodes, _i, _len, _ref;
    args = Array.prototype.slice.call(arguments);
    length = args.length;
    callback = null;
    if (typeof args[length - 1] === 'function') {
      callback = args.pop();
    }
    if (Array.isArray(args[0])) {
      args = args[0];
    }
    remote_nodes = {};
    multis = [];
    migrated_keys = [];
    dest_key = args[0];
    dest_node = this.nodeFor(dest_key);
    dest_client = this.clients[dest_node];
    _ref = args.slice(1);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      arg = _ref[_i];
      node = this.nodeFor(arg);
      if (remote_nodes[node] == null) {
        remote_nodes[node] = [];
      }
      remote_nodes[node].push(arg);
    }
    for (node in remote_nodes) {
      keys = remote_nodes[node];
      if (node === dest_node) {
        continue;
      }
      client = this.clients[node];
      multi = multis[node] = client.multi();
      keys.forEach(function(key) {
        migrated_keys.push(key);
        return multi.migrate([dest_node.host, dest_node.port, key, dest_node.selected_db]);
      });
    }
    return step(function() {
      var group;
      group = this.group();
      return multis.forEach(function(multi) {
        return multi.exec(group());
      });
    }, function(error, groups) {
      if (error) {
        return typeof callback === "function" ? callback(error) : void 0;
      }
      assert(multis.length === groups.length, "wrong number of response");
      return dest_client.sinterstore.call(dest_client, args, function() {
        if (migrated_keys.length > 0) {
          dest_client.del(migrated_keys);
        }
        return callback != null ? callback.apply(this, arguments) : void 0;
      });
    });
  };

  Redison.prototype.zinterstore = function() {
    var arg, args, callback, client, dest_client, dest_key, dest_node, keys, length, migrated_keys, multi, multis, node, number_keys, remote_nodes, _i, _len, _ref;
    args = Array.prototype.slice.call(arguments);
    length = args.length;
    callback = null;
    if (typeof args[length - 1] === 'function') {
      callback = args.pop();
    }
    if (Array.isArray(args[0])) {
      args = args[0];
    }
    remote_nodes = {};
    multis = [];
    migrated_keys = [];
    dest_key = args[0];
    dest_node = this.nodeFor(dest_key);
    dest_client = this.clients[dest_node];
    number_keys = args[1];
    _ref = args.slice(2, 2 + number_keys);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      arg = _ref[_i];
      node = this.nodeFor(arg);
      if (remote_nodes[node] == null) {
        remote_nodes[node] = [];
      }
      remote_nodes[node].push(arg);
    }
    for (node in remote_nodes) {
      keys = remote_nodes[node];
      if (node === dest_node) {
        continue;
      }
      client = this.clients[node];
      multi = multis[node] = client.multi();
      keys.forEach(function(key) {
        migrated_keys.push(key);
        return multi.migrate([dest_node.host, dest_node.port, key, dest_node.selected_db]);
      });
    }
    return step(function() {
      var group;
      group = this.group();
      return multis.forEach(function(multi) {
        return multi.exec(group());
      });
    }, function(error, groups) {
      if (error) {
        return typeof callback === "function" ? callback(error) : void 0;
      }
      assert(multis.length === groups.length, "wrong number of response");
      return dest_client.zinterstore.call(dest_client, args, function() {
        if (migrated_keys.length > 0) {
          dest_client.del(migrated_keys);
        }
        return callback != null ? callback.apply(this, arguments) : void 0;
      });
    });
  };

  Redison.prototype.multi = function() {
    return new Multi(this);
  };

  Redison.prototype.DEL = Redison.del;

  Redison.prototype.MSET = Redison.mset;

  Redison.prototype.ZADD = Redison.zadd;

  Redison.prototype.SINTER = Redison.siner;

  Redison.prototype.SINTERSTORE = Redison.sinterstore;

  Redison.prototype.ZINTERSTORE = Redison.zinterstore;

  Redison.prototype.MULTI = Redison.multi;

  Redison.prototype.nodeFor = function(key) {
    var mod, scope, servers, _ref;
    if (key == null) {
      return;
    }
    assert(typeof key === 'string', "wrong type of sharding key: " + key);
    if (this.servers.scopes) {
      _ref = this.servers.scopes;
      for (scope in _ref) {
        servers = _ref[scope];
        if (!key.match(scope)) {
          continue;
        }
        mod = parseInt(hasher.crc32(key), 16) % servers.length;
        return servers[mod];
      }
    }
    mod = parseInt(hasher.crc32(key), 16) % this.servers["default"].length;
    return this.servers["default"][mod];
  };

  Redison.prototype.on = function(event, callback) {
    var first;
    first = this.servers["default"][0];
    return this.clients[first].on(event, callback);
  };

  return Redison;

})();

Multi = (function() {
  Multi.prototype.multis = {};

  Multi.prototype.interlachen = [];

  Multi.prototype.commands = {};

  Multi.prototype.temp_keys = {};

  function Multi(redison) {
    this.redison = redison;
    this.exec = __bind(this.exec, this);
    this.zinterstore = __bind(this.zinterstore, this);
    this.sinterstore = __bind(this.sinterstore, this);
    this.sinter = __bind(this.sinter, this);
    this.mset = __bind(this.mset, this);
    this.del = __bind(this.del, this);
    SHARDABLE.forEach((function(_this) {
      return function(command) {
        if (command === 'del' || command === 'sinter') {
          return;
        }
        return _this[command] = _this[command.toUpperCase()] = function() {
          var key, multi, node, _base;
          if (Array.isArray(arguments[0])) {
            key = arguments[0][0];
          } else {
            key = arguments[0];
          }
          node = _this.redison.nodeFor(key);
          multi = _this.multis[node];
          if (!multi) {
            multi = _this.multis[node] = _this.redison.clients[node].multi();
          }
          _this.interlachen.push(node);
          if ((_base = _this.commands)[node] == null) {
            _base[node] = 0;
          }
          _this.commands[node] += 1;
          multi[command].apply(multi, arguments);
          return _this;
        };
      };
    })(this));
    UNSHARDABLE.forEach((function(_this) {
      return function(command) {
        if (command === 'exec' || command === 'mset' || command === 'sinterstore' || command === 'zinterstore') {
          return;
        }
        return _this[command] = _this[command.toUpperCase()] = function() {
          throw new Error("" + command + " is not supported");
        };
      };
    })(this));
  }

  Multi.prototype.del = function() {
    var args, callback, length;
    callback = null;
    args = Array.prototype.slice.call(arguments);
    length = args.length;
    if (typeof args[length - 1] === 'function') {
      callback = args.pop();
    }
    if (Array.isArray(args[0])) {
      args = args[0];
    }
    return args.forEach((function(_this) {
      return function(key, idx) {
        var multi, node, _base;
        node = _this.redison.nodeFor(key);
        multi = _this.multis[node];
        if (!multi) {
          multi = _this.multis[node] = _this.redison.clients[node].multi();
        }
        _this.interlachen.push(node);
        if ((_base = _this.commands)[node] == null) {
          _base[node] = 0;
        }
        _this.commands[node] += 1;
        return multi.del.call(multi, args);
      };
    })(this));
  };

  Multi.prototype.mset = function() {
    var arg, args, callback, idx, length, _i, _len;
    args = Array.prototype.slice.call(arguments);
    length = args.length;
    callback = null;
    if (typeof args[length - 1] === 'function') {
      callback = args.pop();
    }
    if (Array.isArray(args[0])) {
      args = args[0];
    }
    if (args.length % 2 !== 0) {
      throw new Error("wrong arguments given");
    }
    for (idx = _i = 0, _len = args.length; _i < _len; idx = _i += 2) {
      arg = args[idx];
      this.set(arg, args[idx + 1]);
    }
    return this;
  };

  Multi.prototype.sinter = function() {
    var arg, args, callback, dest_key, dest_multi, dest_node, keys, length, multi, node, remote_nodes, _base, _i, _len, _ref;
    args = Array.prototype.slice.call(arguments);
    length = args.length;
    callback = null;
    if (typeof args[length - 1] === 'function') {
      callback = args.pop();
    }
    if (Array.isArray(args[0])) {
      args = args[0];
    }
    remote_nodes = {};
    dest_key = args[0];
    dest_node = this.redison.nodeFor(dest_key);
    dest_multi = this.multis[dest_node];
    if (!dest_multi) {
      dest_multi = this.multis[dest_node] = this.redison.clients[dest_node].multi();
    }
    _ref = args.slice(1);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      arg = _ref[_i];
      node = this.redison.nodeFor(arg);
      if (remote_nodes[node] == null) {
        remote_nodes[node] = [];
      }
      remote_nodes[node].push(arg);
    }
    for (node in remote_nodes) {
      keys = remote_nodes[node];
      if (node === dest_node) {
        continue;
      }
      multi = this.multis[node];
      if (!multi) {
        multi = this.multis[node] = this.clients[node].multi();
      }
      keys.forEach((function(_this) {
        return function(key) {
          var _base, _base1;
          if ((_base = _this.temp_keys)[node] == null) {
            _base[node] = [];
          }
          _this.temp_keys[node].push(key);
          multi.migrate([dest_node.host, dest_node.port, key, dest_node.selected_db]);
          _this.interlachen.push(node);
          if ((_base1 = _this.commands)[node] == null) {
            _base1[node] = 0;
          }
          return _this.commands[node] += 1;
        };
      })(this));
    }
    dest_multi.sinterstore.call(dest_multi, args, callback);
    this.interlachen.push(dest_node);
    if ((_base = this.commands)[dest_node] == null) {
      _base[dest_node] = 0;
    }
    return this.commands[dest_node] += 1;
  };

  Multi.prototype.sinterstore = function() {
    var arg, args, callback, dest_key, dest_multi, dest_node, keys, length, multi, node, remote_nodes, _base, _i, _len, _ref;
    args = Array.prototype.slice.call(arguments);
    length = args.length;
    callback = null;
    if (typeof args[length - 1] === 'function') {
      callback = args.pop();
    }
    if (Array.isArray(args[0])) {
      args = args[0];
    }
    remote_nodes = {};
    dest_key = args[0];
    dest_node = this.redison.nodeFor(dest_key);
    dest_multi = this.multis[dest_node];
    if (!dest_multi) {
      dest_multi = this.multis[dest_node] = this.redison.clients[dest_node].multi();
    }
    _ref = args.slice(1);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      arg = _ref[_i];
      node = this.redison.nodeFor(arg);
      if (remote_nodes[node] == null) {
        remote_nodes[node] = [];
      }
      remote_nodes[node].push(arg);
    }
    for (node in remote_nodes) {
      keys = remote_nodes[node];
      if (node === dest_node) {
        continue;
      }
      multi = this.multis[node];
      if (!multi) {
        multi = this.multis[node] = this.clients[node].multi();
      }
      keys.forEach((function(_this) {
        return function(key) {
          var _base, _base1;
          if ((_base = _this.temp_keys)[node] == null) {
            _base[node] = [];
          }
          _this.temp_keys[node].push(key);
          multi.migrate([dest_node.host, dest_node.port, key, dest_node.selected_db]);
          _this.interlachen.push(node);
          if ((_base1 = _this.commands)[node] == null) {
            _base1[node] = 0;
          }
          return _this.commands[node] += 1;
        };
      })(this));
    }
    dest_multi.sinterstore.call(dest_multi, args);
    this.interlachen.push(dest_node);
    if ((_base = this.commands)[dest_node] == null) {
      _base[dest_node] = 0;
    }
    return this.commands[dest_node] += 1;
  };

  Multi.prototype.zinterstore = function() {
    var arg, args, callback, dest_key, dest_multi, dest_node, keys, length, multi, node, number_keys, remote_nodes, _base, _i, _len, _ref;
    args = Array.prototype.slice.call(arguments);
    length = args.length;
    callback = null;
    if (typeof args[length - 1] === 'function') {
      callback = args.pop();
    }
    if (Array.isArray(args[0])) {
      args = args[0];
    }
    remote_nodes = {};
    dest_key = args[0];
    dest_node = this.redison.nodeFor(dest_key);
    dest_multi = this.multis[dest_node];
    number_keys = args[1];
    if (!dest_multi) {
      dest_multi = this.multis[dest_node] = this.redison.clients[dest_node].multi();
    }
    _ref = args.slice(2, 2 + number_keys);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      arg = _ref[_i];
      node = this.redison.nodeFor(arg);
      if (remote_nodes[node] == null) {
        remote_nodes[node] = [];
      }
      remote_nodes[node].push(arg);
    }
    for (node in remote_nodes) {
      keys = remote_nodes[node];
      if (node === dest_node) {
        continue;
      }
      multi = this.multis[node];
      if (!multi) {
        multi = this.multis[node] = this.clients[node].multi();
      }
      keys.forEach((function(_this) {
        return function(key) {
          var _base, _base1;
          if ((_base = _this.temp_keys)[node] == null) {
            _base[node] = [];
          }
          _this.temp_keys[node].push(key);
          multi.migrate([dest_node.host, dest_node.port, key, dest_node.selected_db]);
          _this.interlachen.push(node);
          if ((_base1 = _this.commands)[node] == null) {
            _base1[node] = 0;
          }
          return _this.commands[node] += 1;
        };
      })(this));
    }
    dest_multi.zinterstore.call(dest_multi, args);
    this.interlachen.push(dest_node);
    if ((_base = this.commands)[dest_node] == null) {
      _base[dest_node] = 0;
    }
    return this.commands[dest_node] += 1;
  };

  Multi.prototype.exec = function(callback) {
    var nodes, self;
    nodes = Object.keys(this.multis);
    self = this;
    return step(function() {
      var group;
      group = this.group();
      return nodes.forEach(function(node) {
        return self.multis[node].exec(group());
      });
    }, function(error, groups) {
      var keys, node, results, _ref;
      _ref = self.temp_keys;
      for (node in _ref) {
        keys = _ref[node];
        self.redison[node].del(keys);
      }
      if (error) {
        return typeof callback === "function" ? callback(error) : void 0;
      }
      assert(nodes.length === groups.length, "wrong number of response");
      results = [];
      groups.forEach(function(results, index) {
        node = nodes[index];
        return assert(results.length === self.commands[node], "" + node + " is missing results");
      });
      self.interlachen.forEach(function(node) {
        var index;
        index = nodes.indexOf(node);
        return results.push(groups[index].shift());
      });
      return typeof callback === "function" ? callback(null, results) : void 0;
    });
  };

  Multi.prototype.DEL = Multi.del;

  Multi.prototype.MSET = Multi.mset;

  Multi.prototype.SINTER = Multi.siner;

  Multi.prototype.SINTERSTORE = Multi.sinterstore;

  Multi.prototype.ZINTERSTORE = Multi.zinterstore;

  Multi.prototype.EXEC = Multi.exec;

  return Multi;

})();

module.exports = Redison;
